KOGITO-8994: drools/optaplanner version update in kie-benchmarks
kiegroup/kie-benchmarks pull request #231
Opened 2023-04-19 14:56 UTC by mbiarnes

2023-04-19 20:44 UTC, radtriste requested changes

2023-04-19 20:44 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +import org.kie.jenkins.jobdsl.Utils
```suggestion
import org.kie.jenkins.jobdsl.model.JobType
import org.kie.jenkins.jobdsl.utils.JobParamsUtils
import org.kie.jenkins.jobdsl.KogitoJobTemplate
import org.kie.jenkins.jobdsl.Utils
```

2023-04-19 20:44 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +        REPO_NAME: 'drools',
please use another name. `REPO_NAME` is used to identify the repository against which you run. Here it is `kie-benchmarks`

2023-04-19 20:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +}
Make this more dynamic.
For example, you could have as an environment varialble a `DEPENDENCY_PROJECT`
and then you would have:

```suggestion
String getDroolsVersion() {
    return params.DROOLS_VERSION
}

String getVersion() {
    return params."${DEPENDENCY_PROJECT.toUpperCase()}_VERSION"
}

String getDependencyProject() {
    return env.DEPENDENCY_PROJECT
}
```

2023-04-19 20:44 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +setupOptaPlannerUpdateJob()
```suggestion
setupUpdateDependencyJob('optaplanner')
setupUpdateDependencyJob('drools')
```

Those 2 methods are linked to one Jenkinsfile. You could make it more generic (goes with the `DEPENDENCY_PROJECT` comment)
and have a single method `setupUpdateDependencyJob`

2023-04-20 07:29 UTC, dupliaka approved these changes
LGTM to me

2023-04-20 07:40 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +}
could be yes. This is just an example. Adapt it as you wish ;)

2023-04-21 13:53 UTC, radtriste approved these changes
minor comments

2023-04-21 13:53 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +// update drools/optaplanner version in kie-benchmarks
```suggestion
```

2023-04-21 13:53 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +        UPDATE_REPO_NAME: "${updateRepoName}",
unsused. can be removed

2023-04-21 13:53 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +    return params."${getDependencyProject().toUpperCase()}_VERSION"
I just think that you don't even need the dependency name for the parameter.
The parameter could be just named something like `NEW_VERSION`

2023-04-21 13:53 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +                        String commitMsg = "bumped up ${getDependencyProject()} version to next SNAPSHOT"
```suggestion
                        String commitMsg = "bumped up ${getDependencyProject()} version to ${getVersion()}"
```

2023-04-25 08:55 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +        label 'kie-rhel8 && !built-in'
Thinking that it should be enough.
`kie-rhel8` is a 16G mem node, and we don't need it here IMO
```suggestion
        label 'rhel8 && !built-in'
```

2023-04-25 08:55 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +                        checkoutRepo("${repoName}", "${getTargetBranch()}")
```suggestion
                        checkoutRepo(repoName, getTargetBranch())
```

2023-04-25 08:57 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.bump-up-version
> +                    dir("${repoName}") {
```suggestion
                    dir("${repoName}") {
                        deleteDir()
```

2023-04-25 08:57 UTC, radtriste approved these changes

2023-04-25 11:38 UTC, merged